### ISSUE TITLE
Nothing is Loading

### ISSUE THREAD

**Issue by ro2alive** [niturobert/gmailkit#5]
Nothing is loading when I open the website or HTML file. A screen recording will be attached to my screen when I load in.
[Screen recording 2023-04-03 1.30.36 PM.webm](https://user-images.githubusercontent.com/119982112/229596165-fec962a2-f298-4ad1-8584-588c49d6b7fd.webm)

**Comment by ro2alive** [comment]
Also, just a side note. This is made nicely and I would choose this over the default Reddit skin.

**Comment by niturobert** [comment]
Hey there, thanks for the request. Could you provide me the logs of the developer console from your browser so that I can look into it?

**Comment by ro2alive** [comment]
Im on a school chromebook so I can't get to that unfortanaly.

**Comment by niturobert** [comment]
Can you connect to reddit.com normally? I was thinking that maybe you're facing a firewall restriction.

**Comment by ro2alive** [comment]
> Can you connect to reddit.com normally? I was thinking that maybe you're facing a firewall restriction.

No, they blocked it at my school. I think your right.

**Comment by cantbethamed** [comment]
Hello! I am facing this issue where the posts aren't loading, but differently from the OP, I have access to reddit at work.

<img width="1014" height="613" alt="Image" src="https://github.com/user-attachments/assets/b2a8a912-374d-47a2-8084-e9e619fdb258" />
